import { Card, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { BrainCircuit, Target, Users, TrendingUp } from 'lucide-react';

const features = [
  {
    icon: <BrainCircuit className="h-10 w-10 text-primary" />,
    title: 'AI Recommendations',
    description: 'Personalized development plans generated by our advanced AI to match individual career goals and skills.',
  },
  {
    icon: <TrendingUp className="h-10 w-10 text-primary" />,
    title: 'Career Path Mapping',
    description: 'Visualize potential career trajectories within your organization and the steps needed to get there.',
  },
  {
    icon: <Target className="h-10 w-10 text-primary" />,
    title: 'Skill Gap Analysis',
    description: 'Identify critical skill gaps at both individual and team levels to inform training strategies.',
  },
  {
    icon: <Users className="h-10 w-10 text-primary" />,
    title: 'Manager Insights',
    description: 'Empower managers with actionable insights to guide their teams\' growth and development effectively.',
  },
];

export default function FeaturesSection() {
  return (
    <section id="features" className="py-20 sm:py-32 bg-secondary">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            A Better Way to Foster Talent
          </h2>
          <p className="mt-4 text-lg text-muted-foreground">
            TalentFlow AI provides the tools you need to build a future-ready workforce.
          </p>
        </div>
        <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-4">
          {features.map((feature, index) => (
            <Card
              key={feature.title}
              className="group transform-gpu bg-card/50 transition-all duration-300 hover:-translate-y-2 hover:shadow-2xl hover:shadow-primary/20 animate-in fade-in slide-in-from-bottom-5"
              style={{ animationDelay: `${index * 150}ms` }}
            >
              <CardHeader className="items-center text-center p-8">
                <div className="rounded-full bg-primary/10 p-4 mb-4">{feature.icon}</div>
                <CardTitle className="text-xl font-semibold">{feature.title}</CardTitle>
                <CardDescription className="mt-2 text-base">{feature.description}</CardDescription>
              </CardHeader>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
}
